ProductsPage_Definitions:
  InventoryItemNames:
    ElementCountShouldBe: 6
    EachInGroupShouldContain:
      - Sauce Labs Backpack
      - Sauce Labs Bike Light
      - Sauce Labs Bolt T-Shirt
      - Sauce Labs Fleece Jacket
      - Sauce Labs Onesie
      - Test.allTheThings() T-Shirt (Red)
  InventoryItemImageLink:
    ElementCountShouldBe: 6
  InventoryItemImages:
    ElementCountShouldBe: 6
    ImageGroupAttributes:
      BackPack:
        DefaultOrder: 1
        Alt: Sauce Labs Backpack
      BikeLight:
        DefaultOrder: 2
        Alt: Sauce Labs Bike Light
      BoltShirt:
        DefaultOrder: 3
        Alt: Sauce Labs Bolt T-Shirt
      FleeceJacket:
        DefaultOrder: 4
        Alt: Sauce Labs Fleece Jacket
      Onesie:
        DefaultOrder: 5
        Alt: Sauce Labs Onesie
      TestAllThingsShirt:
        DefaultOrder: 6
        Alt: Test.allTheThings() T-Shirt (Red)
